config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present? && request.subdomain != "www"
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank? || request.subdomain == 'www'
  end
end


Rails.application.routes.draw do
  resources :home

  constraints(SubdomainBlank) do
    root to: "home#index"
    resources :tenants
  end

  constraints(SubdomainPresent) do
    resources :dashboard
    resources :comments
    resources :tasks
    resources :projects

    # root to: "dashboard#index"
    get "/", to: "dashboard#index"
    # other stuff that you want...
  end


  devise_for :users, controllers: {sessions: "users/sessions"}

  # root to: "home#index"
end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
  resourcify

  has_many :roles, as: :resource
  has_many :collaborators, through: :roles, source: :users
  has_many :projects

  validates :name, :slug, presence: true

  before_validation :ensure_slug

  def ensure_slug
    self.slug = name.parameterize if slug.blank? && name.present?
  end

  def url(path='')
    "http://#{self.slug}.saas.dev#{path}"
  end
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: [:show, :edit, :update, :destroy]

  # GET /tenants
  # GET /tenants.json
  def index
    @user_roles = current_user.roles.in_tenant
    # @tenants = Tenant.all
  end

  # GET /tenants/1
  # GET /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants
  # POST /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)

    respond_to do |format|
      if @tenant.save
        current_user.add_role(:owner, @tenant)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully created.' }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1
  # PATCH/PUT /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to @tenant, notice: 'Tenant was successfully updated.' }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1
  # DELETE /tenants/1.json
  def destroy
    @tenant.destroy
    respond_to do |format|
      format.html { redirect_to tenants_url, notice: 'Tenant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tenant_params
      params.require(:tenant).permit(:name, :description, :slug)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_for(@tenant) do |f| %>
  <% if @tenant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
      <% @tenant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :slug, "Subdomain" %><br>
    http://<%= f.text_field :slug %> .saas.dev
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tenants/edit.html.erb
<h1>Editing Tenant</h1>

<%= render 'form' %>

<%= link_to 'Show', @tenant %> |
<%= link_to 'Back', tenants_path %>

app/views/tenants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your organisations dude!</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_roles.each do |role| %>
      <% tenant = role.resource %>
    <%# @tenants.each do |tenant| %>
      <tr>
        <td><%= tenant.name %></td>
        <td><%= tenant.description %></td>
        <td><%= link_to tenant.url, tenant.url %></td>
        <td><%= link_to 'Show', tenant %></td>
        <td><%= link_to 'Edit', edit_tenant_path(tenant) %></td>
        <td><%= link_to 'Destroy', tenant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tenant', new_tenant_path %>

app/views/tenants/new.html.erb
<div class="container">
  <h1>New Organisation</h1>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag 'yu.png', width: "50%" %>
    </div>
    <div class="col-md-9">
      <%= render 'form' %>
      <%= link_to 'Back', tenants_path %>
    </div>
  </div>
</div>

app/views/tenants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tenant.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tenant.description %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tenant.slug %>
</p>

<%= link_to 'Edit', edit_tenant_path(@tenant) %> |
<%= link_to 'Back', tenants_path %>